AWSTemplateFormatVersion: "2010-09-09"

Description: "Componentes necesarios para exponer un Frontend"

Parameters:

  ClusterName:
    Type: String
    Description: Nombre del cluster en el que se creará el Frontend

  ContainerPort:
    Type: Number
    Default: 8000
    Description: port number exposed from the container image.

  NumeroBalanceador:
    Type: String
    Default: "1"

  DominioBase:
    Type: String
    Default: "test.timelineage.site"
    Description: "<HTTPS> Dominio base (el de la HostedZone). Ejemplo: test.timelineage.site"

  Route53HostedZoneId:
    Default: "Z05524491VQ38G93MIPQD"
    Type: String
    Description: "<HTTPS> ID de la HostedZone dueña del dominio base. Ejemplo: test.timelineage.site - Z05524491VQ38G93MIPQD"

  SubdominioBalanceador:
    Default: "webs1"
    Type: String
    Description: "<HTTPS> Subdominio del balanceador. Ejemplo: webs1"

  WebPath:
    Type: String
    Description: "<HTTP> Path en el que escucha tu aplicación por HTTP. Ejemplo: /test"
    Default: ""


  HealthPath:
    Type: String
    Description: Path de health del servicio

  NombreVPC:
    Type: String
    Default: NMP-Servicios

  PrioridadListener:
    Type: Number
    Description: Prioridad de de la regla en el listener. No se debe repetir.

  ServiceName:
    Type: String
    Default: paketo
    Description: Nombre del microservicio

  TaskDefinitionARN:
    Type: String
    Description: ARN de Task Definition


Conditions:
  NoDominioBase: !Equals [ !Ref Route53HostedZoneId, ""]
  NoRoute53HostedZoneId: !Equals [ !Ref Route53HostedZoneId, ""]
  NoSubdominioBalanceador: !Equals [ !Ref SubdominioBalanceador, ""]
  NoHTTPS: !Or [Condition: NoDominioBase, Condition: NoRoute53HostedZoneId, Condition: NoSubdominioBalanceador] 
  HTTPS: !Not [Condition: NoHTTPS]

Resources:
  
  TaskLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub /ecs/${ClusterName}/${ServiceName}
      RetentionInDays: 30

  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SG para ms
      GroupName: !Sub ${ServiceName}-sg
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/16"
          FromPort: !Ref ContainerPort
          IpProtocol: tcp
          ToPort: !Ref ContainerPort
      VpcId: !ImportValue
        "Fn::Sub": ${NombreVPC}-VPC

  ElasticLoadBalancingV2TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 300
      HealthCheckPath: !Ref HealthPath
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: "200"
      Name: !Sub ${ServiceName}-1
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: "false"
        - Key: deregistration_delay.timeout_seconds
          Value: "300"
        - Key: stickiness.app_cookie.cookie_name
          Value: ""
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: "86400"
        - Key: slow_start.duration_seconds
          Value: "0"
        - Key: stickiness.app_cookie.duration_seconds
          Value: "86400"
        - Key: load_balancing.algorithm.type
          Value: round_robin
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: !ImportValue
        "Fn::Sub": ${NombreVPC}-VPC

  FrontALBListenerRuleHTTP:
    Condition: NoHTTPS
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref ElasticLoadBalancingV2TargetGroup
                Weight: 1
      Conditions:
        - 
          Field: path-pattern
          Values: 
            - !Sub "${WebPath}*"
      ListenerArn: 
        Fn::ImportValue: !Sub "${NombreVPC}-FrontAlbListenerHTTP${NumeroBalanceador}"
      Priority: !Ref PrioridadListener

  FrontALBListenerRuleHTTPS:
    Condition: HTTPS
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref ElasticLoadBalancingV2TargetGroup
                Weight: 1
      Conditions:
        - Field: host-header
          Values:
            - "Fn::Sub": "${ServiceName}.${SubdominioBalanceador}.${DominioBase}"
      ListenerArn:
        Fn::ImportValue: !Sub "${NombreVPC}-FrontAlbListenerHTTPS${NumeroBalanceador}"
      Priority: !Ref PrioridadListener

  FrontSubDomain:
    Condition: HTTPS
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Comment: !Sub "Subdominio para Frontend ${ServiceName}"
      RecordSets:
        - Name: !Sub "${ServiceName}.${SubdominioBalanceador}.${DominioBase}"
          Type: A
          AliasTarget:
            DNSName:
              Fn::ImportValue: !Sub "${NombreVPC}-FrontAlbDNS${NumeroBalanceador}"
            EvaluateTargetHealth: true
            HostedZoneId:
              Fn::ImportValue: !Sub "${NombreVPC}-FrontAlbHostedZone${NumeroBalanceador}"

  ECSServiceHTTP:
    Condition: NoHTTPS
    Type: "AWS::ECS::Service"
    DependsOn:
      - TaskLogGroup
      - FrontALBListenerRuleHTTP
    Properties:
      ServiceName: !Sub "${ServiceName}-http"
      Cluster: !Ref ClusterName
      LoadBalancers: 
        - 
          TargetGroupArn: !Ref ElasticLoadBalancingV2TargetGroup
          ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
      DesiredCount: 1
      LaunchType: "FARGATE"
      PlatformVersion: "1.4.0"
      TaskDefinition: !Ref TaskDefinitionARN
      DeploymentConfiguration: 
          MaximumPercent: 200
          MinimumHealthyPercent: 100
          DeploymentCircuitBreaker:
            Enable: True
            Rollback: False
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: "DISABLED"
          SecurityGroups: 
            - !Ref EC2SecurityGroup
          Subnets: 
            - Fn::ImportValue: !Sub "${NombreVPC}-PrivateSubnet1a"
      HealthCheckGracePeriodSeconds: 0
      SchedulingStrategy: "REPLICA"
      DeploymentController: 
          Type: "ECS"

  ECSServiceHTTPS:
    Condition: HTTPS
    Type: "AWS::ECS::Service"
    DependsOn:
      - TaskLogGroup
      - FrontALBListenerRuleHTTPS
    Properties:
      ServiceName: !Sub "${ServiceName}-https"
      Cluster: !Ref ClusterName
      LoadBalancers: 
        - 
          TargetGroupArn: !Ref ElasticLoadBalancingV2TargetGroup
          ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
      DesiredCount: 1
      LaunchType: "FARGATE"
      PlatformVersion: "1.4.0"
      TaskDefinition: !Ref TaskDefinitionARN
      DeploymentConfiguration: 
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: "DISABLED"
          SecurityGroups: 
            - !Ref EC2SecurityGroup
          Subnets: 
            - Fn::ImportValue: !Sub "${NombreVPC}-PrivateSubnet1a"
      HealthCheckGracePeriodSeconds: 0
      SchedulingStrategy: "REPLICA"
      DeploymentController: 
          Type: "ECS"
